### ISSUE TITLE
使用 daili 后, 请求京东接口报错, 是urllib3的bug

### ISSUE THREAD

**Issue by taoing** [hyzaw/JDMemberCloseLinks#1]
requests依赖的urllib3最新版本存在bug, 建议使用较低版本.
在requirements.txt中指定urllib3版本: urllib3==1.25.7, 即可避免系统 daili 问题

**Comment by hyzaw** [comment]
好的 刚刚放学回家 下个版本修复

**Comment by hyzaw** [comment]
已更新
