### ISSUE TITLE
大佬教程能详细点吗 小白看不懂啊

### ISSUE THREAD

**Issue by fruitbook** [hyzaw/JDMemberCloseLinks#4]

**Comment by hyzaw** [comment]
直接去release找exe啊

**Comment by fruitbook** [comment]
> 已释放法金

我纯小白 release找exe 是需要先下载什么软件吗

**Comment by hyzaw** [comment]
> > 已释放法金
> 
> 我纯小白 release找exe 是需要先下载什么软件吗

https://github.com/hyzaw/JDMemberCloseLinks/releases/download/v0.0.5/JDMemberCloseLinks_windows_amd64.exe

**Comment by fruitbook** [comment]
> > > 已释放法金
> > 
> > 
> > 我纯小白 release找exe 是需要先下载什么软件吗
> 
> https://github.com/hyzaw/JDMemberCloseLinks/releases/download/v0.0.5/JDMemberCloseLinks_windows_amd64.exe

这个获取到注销地址后 我粘贴到网址栏 提示网络请求失败  是我还有哪里没弄吗

**Comment by hyzaw** [comment]
> > > > 已释放法金
> > > 
> > > 
> > > 我纯小白 release找exe 是需要先下载什么软件吗
> > 
> > 
> > https://github.com/hyzaw/JDMemberCloseLinks/releases/download/v0.0.5/JDMemberCloseLinks_windows_amd64.exe
> 
> 这个获取到注销地址后 我粘贴到网址栏 提示网络请求失败 是我还有哪里没弄吗

先去 home.m.jd.com 登录京东
